version: "3"

services:
  mysql:
    image: mysql:$MYSQL_TAG
    networks:
      - libsfm-proxy
    container_name: "${PROJECT_NAME}_mysql"
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - "./dbdata:/var/lib/mysql"
    restart: always

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    networks:
      - libsfm-proxy
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      #      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S opensmtpd:25
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      PHP_MEMORY_LIMIT: 1024M
      PHP_DATE_TIMEZONE: Asia/Shanghai
      PHP_POST_MAX_SIZE: 64M
      PHP_UPLOAD_MAX_FILESIZE: 64M
      #      PHP_ERROR_REPORTING: -1
      COLUMNS: 80 # Set 80 columns for docker exec -it.
    ## Read instructions at https://wodby.com/stacks/drupal/docs/local/xdebug/
    #      PHP_XDEBUG: 1
    #      PHP_XDEBUG_DEFAULT_ENABLE: 1
    #      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
    #      PHP_IDE_CONFIG: serverName=my-ide
    #      PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ Mac/Win
    #      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
    #      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS, Docker < 18.03
    #      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows, Docker < 18.03
    #      PHP_XDEBUG_REMOTE_LOG: /tmp/php-xdebug.log
    volumes:
      - ./drupal:/var/www/html
  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    expose:
      - "80"
      - "443"
    networks:
      - libsfm-proxy
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    #      NGINX_DRUPAL_FILE_PROXY_URL: http://example.com
    volumes:
      - ./drupal:/var/www/html
    labels:
      - "traefik.enable=true"
      # - "traefik.http.middlewares.cnjws-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.cnjws-strip.stripprefix.prefixes=/cnjws"
      - "traefik.http.routers.cnjws-http.entrypoints=web"
      - "traefik.http.routers.cnjws-http.rule=Host(`web.example.com`)"
      # - "traefik.http.routers.cnjws-http.middlewares=cnjws-https@docker"
      # - "traefik.http.routers.cnjws-http.middlewares=cnjws-strip@docker"
      # - "traefik.http.routers.cnjws.entrypoints=web-secure"
      # - "traefik.http.routers.cnjws.rule=Host(`web.example.com`) && PathPrefix(`/cnjws`)"
      # - "traefik.http.routers.cnjws.middlewares=cnjws-strip@docker"
      # - "traefik.http.routers.cnjws.tls=true"
      # - "traefik.http.routers.cnjws.tls.certresolver=default"

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    networks:
      - libsfm-proxy
    environment:
      PMA_HOST: $DB_HOST
      # PMA_USER: $DB_USER
      # PMA_PASSWORD: $DB_PASSWORD
      PMA_ARBITRARY: 1
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
      PHP_POST_MAX_SIZE: 64M
    labels:
      - "traefik.enable=true"
      # - "traefik.http.middlewares.cnjwspma-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.pma-strip.stripprefix.prefixes=/cnjwspma"
      - "traefik.http.routers.cnjwspma-http.entrypoints=web"
      - "traefik.http.routers.cnjwspma-http.rule=Host(`pma.example.com`)"
      # - "traefik.http.routers.cnjwspma-http.middlewares=cnjwspma-https@docker"
      # - "traefik.http.routers.pma-http.middlewares=pma-strip@docker"
      # - "traefik.http.routers.cnjwspma.entrypoints=web-secure"
      # - "traefik.http.routers.cnjwspma.rule=Host(`pma.example.com`) && PathPrefix(`/cnjwspma`)"
      # - "traefik.http.routers.cnjwspma.middlewares=pma-strip@docker"
      # - "traefik.http.routers.cnjwspma.tls=true"
      # - "traefik.http.routers.cnjwspma.tls.certresolver=default"
networks:
  libsfm-proxy:
    external:
      name: libsfm-proxy
