[log]
  level = "DEBUG"

[providers]
  [providers.docker]
    exposedByDefault = false
    endpoint = "unix:///var/run/docker.sock"
    network = "libsfm-proxy"
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"

[api]
  insecure = true
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"
  [entryPoints.mysql]
    address = ":3306"
